In [138]:
import numpy as np
from pandas import read_csv

# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    print("pred", X, W, b)
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # the values for the current linear model
    values = np.matmul(X, W) + b
    
    print(W)
    print(b)
    # the classificatrions of the current model
    y1 = np.heaviside(values, 1)
    feedback = (y.reshape(-1, 1) - y1)*learn_rate
    print(np.hstack([X, values]))
    
    # W with feedback
    W = (W + np.matmul(feedback.T, X).T)
    
    b = (b + feedback.sum())

    
    # Fill in code
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines


# this function returns a DataFrame
data = read_csv("data.csv", header=None).values
X = data[:, 0:2]
y = data[:, 2]

trainPerceptronAlgorithm(X, y, num_epochs=3)

[[0.37454012]
 [0.95071431]]
1.731993941811405
[[ 0.78051    -0.063669    1.96379522]
 [ 0.28774     0.29139     2.11679276]
 [ 0.40714     0.17878     2.05445291]
 [ 0.2923      0.4217      2.24238824]
 [ 0.50922     0.35256     2.2579011 ]
 [ 0.27785     0.10802     1.93875607]
 [ 0.27527     0.33223     2.15094941]
 [ 0.43999     0.31245     2.19383853]
 [ 0.33557     0.42984     2.26633341]
 [ 0.23448     0.24986     2.05736159]
 [ 0.0084492   0.13658     1.86500707]
 [ 0.12419     0.33595     2.09790055]
 [ 0.25644     0.42624     2.23327348]
 [ 0.4591      0.40426     2.28828108]
 [ 0.44547     0.45117     2.3277741 ]
 [ 0.42218     0.20118     2.08138199]
 [ 0.49563     0.21445     2.12150794]
 [ 0.30848     0.24306     2.0786127 ]
 [ 0.39707     0.44438     2.30319101]
 [ 0.32945     0.39217     2.22822781]
 [ 0.40739     0.40271     2.26744   ]
 [ 0.3106      0.50702     2.33035727]
 [ 0.49638     0.45384     2.34938035]
 [ 0.10073     0.32053     2.07445382]
 [ 0.69907     0.

[(array([-0.05239463]), array([-2.04919443])),
 (array([1.23772563]), array([-2.90815949])),
 (array([-6.69291623]), array([2.37208027]))]

In [139]:
np.random.seed(42)

def perceptronStep2(X, y, W, b, learn_rate = 0.01):
    
    print(W)
    print(b)
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        print("", X[i], (np.matmul(X[i],W)+b)[0])
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    print()
    return W, b

# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm2(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep2(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

trainPerceptronAlgorithm2(X, y, num_epochs=3)

[[0.37454012]
 [0.95071431]]
1.731993941811405
pred [ 0.78051  -0.063669] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [ 0.78051  -0.063669] 1.963795220798147
pred [0.28774 0.29139] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [0.28774 0.29139] 2.1167927573533305
pred [0.40714 0.17878] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [0.40714 0.17878] 2.054452909498885
pred [0.2923 0.4217] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [0.2923 0.4217] 2.2423882415635505
pred [0.50922 0.35256] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [0.50922 0.35256] 2.257901096998739
pred [0.27785 0.10802] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [0.27785 0.10802] 1.9387560732115439
pred [0.27527 0.33223] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [0.27527 0.33223] 2.150949414345085
pred [0.43999 0.31245] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [0.43999 0.31245] 2.193838533740834
pred [0.33557 0.42984] [[0.37454012]
 [0.95071431]] 1.731993941811405
 [0.33557 0.42984] 2

 [0.69176 0.60865] 0.2706963411286507
pred [0.66408 0.92075] [[-0.46385878]
 [ 0.10037211]] 0.5119939418114039
 [0.66408 0.92075] 0.2963722194004904
pred [0.65973 0.66666] [[-0.47049958]
 [ 0.09116461]] 0.5019939418114039
 [0.65973 0.66666] 0.25236704964680884
pred [0.64574 0.56845] [[-0.47709688]
 [ 0.08449801]] 0.4919939418114039
 [0.64574 0.56845] 0.2319462935196165
pred [0.89639 0.7085 ] [[-0.48355428]
 [ 0.07881351]] 0.48199394181140387
 [0.89639 0.7085 ] 0.10438008902041662
pred [0.85476 0.63167] [[-0.49251818]
 [ 0.07172851]] 0.47199394181140386
 [0.85476 0.63167] 0.09631784693332696
pred [0.62091 0.80424] [[-0.50106578]
 [ 0.06541181]] 0.46199394181140385
 [0.62091 0.80424] 0.20348397882303043
pred [0.79057 0.56108] [[-0.50727488]
 [ 0.05736941]] 0.45199394181140384
 [0.79057 0.56108] 0.08314646556703875
pred [0.58935 0.71582] [[-0.51518058]
 [ 0.05175861]] 0.44199394181140383
 [0.58935 0.71582] 0.1754221119494429
pred [0.56846 0.7406 ] [[-0.52107408]
 [ 0.04460041]] 0.43199394

[(array([-0.05239463]), array([-2.04919443])),
 (array([1.23772563]), array([-2.90815949])),
 (array([-39.47663703]), array([23.57864461]))]